{% set name = "dakota" %}
{% set version = "6.10" %}
{% set sha256sum = "2a0d2f426c0f369cfa3c0b341061553e651a6f60377a59f83251d9d3c3821bad" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: dakota{{ version }}.tar.gz
    url: https://dakota.sandia.gov/sites/default/files/distributions/public/dakota-{{ version }}-release-public.src.tar.gz
    sha256: {{ sha256sum }}
    patches:
        - surfpack_py_bindings.patch
        - gsl.patch
        - python.patch
        - colin_boost170.patch

build:
    number: 0
    skip: true  # [win or osx or py<37]

requirements:
    build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
    host:
        - openmpi
        - pybind11
        - boost-cpp
        - libblas
        - libcblas
        - python
        - perl
        - numpy
        - swig
        - doxygen
        - gsl
        - hdf5
        # - trilinos  # needs newer trilinos
    run:
        - openmpi
        - boost-cpp
        - python
        - {{ pin_compatible("numpy") }}
        - nomkl
        - openblas
        - gsl
        # - trilinos
test:
    imports:
        - dakota
        - dakota.interfacing
        - dakota.interfacing.dprepro
        - pysurfpack


about:
    home: https://dakota.sandia.gov
    license: LGPL-3.0
    license_family: LGPL
    license_file: LICENSE
    summary: 'The Dakota project delivers software for optimization and uncertainty quantification.'
    description: |
        The Dakota project delivers both state-of-the-art research and robust, 
        usable software for optimization and UQ. Broadly, the Dakota software's 
        advanced parametric analyses enable design exploration, model calibration, 
        risk analysis, and quantification of margins and uncertainty with computational
        models. The Dakota toolkit provides a flexible, extensible interface 
        between such simulation codes and its iterative systems analysis methods.
    doc_url: https://dakota.sandia.gov/content/610-reference-manual
    dev_url: https://dakota.sandia.gov/

extra:
    recipe-maintainers:
        - looooo
