travis:
  secure:
    BINSTAR_TOKEN: MvLmsdubqY5C0czRx+byDSwY7B6SBYY8R/hVborhsFV0hFglr1bVXJa73fRMJ/UlsBI9ikfxS/aMeS4CRBTZIBGJBJqB59frzT6lAa8AqcY/xC3UUTZzBMvKNaRJ9a7+UYzao+WdTptn9dR1DMB2EHPvH6QBiK6GeWH5HMd6M6KmLiBSQ8M3R/pGFldzyOgo/K5LHdIMGF0APBa6jj0YQcJa25IHU1QwyBT8fQZdSVKxqwJWX/cOldh5D42d8vE4TWP/ADOxKTmF/ShVTWWx/PEeU7CjyN3yJtsPnsyc6pln0sSydiVVCs0w9IDCayUPD1kNhRjyUEgWR8ZjXftUMx0jD4khZs3UpLB8ki2WdhwgMvF4GDNdXMhBS7bhJXmpZD340GiJrexakIsD04NYa7cQ4wRZOoI67jvG32jbB88OsBMXhg5FphpU+TdCzN46Jz6g6eArioEzZqAYo2s4gLAGTffJQ8wa3Y2dDtTmRZYNPZevNvVHZ5uuJcAIz686Pzkwd1Fb720WaMqZSZRm2mwr8nOEE2joVgw/nyi0JkmmA0tpfVp3XnP0eCUlXHbOWhW8OKuxbrwjBLe8j7flsIyxb5871cw5AyPooCkUDtekfIjNkFz8xk7Z374g8wwLfQGQi5NuGYHk2dr+USDchP6byWCTiQ5soBh/yZ+IYbc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
